# Site / Personal / Description settings
title: Michael Liquori | Developer
email: liquori@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: mliq
github_username:  mliq

# Time & Site setup
baseurl: "" # the subpath of your site, e.g. /
url: "http://mliq.github.io" # the base hostname & protocol for your site
TZ: 'America/Chicago'

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# put in blog subdirectory
permalink: /:categories/:year/:month/:day/:title.html
